services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php_apache_sqlite
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html 
    restart: unless-stopped
