services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        HOST_UID: 1000 # Check and adjust as needed - Linux: id -u
        HOST_GID: 1000 # Check and adjust as needed - Linux: id -g
    container_name: php_apache_sqlite
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html 
    restart: unless-stopped
